// <auto-generated />
namespace Lab4App.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixingiD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingiD));
        
        string IMigrationMetadata.Id
        {
            get { return "201710072303551_Fixing iD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
